[project]
name = "smartcomps"
version = "0.1.0"
description = ""
authors = [
    {name = "Ryan-Fue",email = "ryanfue@ucla.edu"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "yfinance (>=1.2.0,<2.0.0)",
    "pandas (>=3.0.1,<4.0.0)",
    "scikit-learn (>=1.8.0,<2.0.0)",
    "ipykernel (>=7.2.0,<8.0.0)",
    "requests (>=2.33.1,<3.0.0)",
    "tqdm (>=4.67.3,<5.0.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.2,<10.0.0)"
]
